#line 1 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.cc"

#line 3 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer hspice__create_buffer
#define yy_delete_buffer hspice__delete_buffer
#define yy_scan_buffer hspice__scan_buffer
#define yy_scan_string hspice__scan_string
#define yy_scan_bytes hspice__scan_bytes
#define yy_init_buffer hspice__init_buffer
#define yy_flush_buffer hspice__flush_buffer
#define yy_load_buffer_state hspice__load_buffer_state
#define yy_switch_to_buffer hspice__switch_to_buffer
#define yypush_buffer_state hspice_push_buffer_state
#define yypop_buffer_state hspice_pop_buffer_state
#define yyensure_buffer_stack hspice_ensure_buffer_stack
#define yy_flex_debug hspice__flex_debug
#define yyin hspice_in
#define yyleng hspice_leng
#define yylex hspice_lex
#define yylineno hspice_lineno
#define yyout hspice_out
#define yyrestart hspice_restart
#define yytext hspice_text
#define yywrap hspice_wrap
#define yyalloc hspice_alloc
#define yyrealloc hspice_realloc
#define yyfree hspice_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define hspice__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer hspice__create_buffer
#endif

#ifdef yy_delete_buffer
#define hspice__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer hspice__delete_buffer
#endif

#ifdef yy_scan_buffer
#define hspice__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer hspice__scan_buffer
#endif

#ifdef yy_scan_string
#define hspice__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string hspice__scan_string
#endif

#ifdef yy_scan_bytes
#define hspice__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes hspice__scan_bytes
#endif

#ifdef yy_init_buffer
#define hspice__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer hspice__init_buffer
#endif

#ifdef yy_flush_buffer
#define hspice__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer hspice__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define hspice__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state hspice__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define hspice__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer hspice__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define hspice_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state hspice_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define hspice_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state hspice_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define hspice_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack hspice_ensure_buffer_stack
#endif

#ifdef yylex
#define hspice_lex_ALREADY_DEFINED
#else
#define yylex hspice_lex
#endif

#ifdef yyrestart
#define hspice_restart_ALREADY_DEFINED
#else
#define yyrestart hspice_restart
#endif

#ifdef yylex_init
#define hspice_lex_init_ALREADY_DEFINED
#else
#define yylex_init hspice_lex_init
#endif

#ifdef yylex_init_extra
#define hspice_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra hspice_lex_init_extra
#endif

#ifdef yylex_destroy
#define hspice_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy hspice_lex_destroy
#endif

#ifdef yyget_debug
#define hspice_get_debug_ALREADY_DEFINED
#else
#define yyget_debug hspice_get_debug
#endif

#ifdef yyset_debug
#define hspice_set_debug_ALREADY_DEFINED
#else
#define yyset_debug hspice_set_debug
#endif

#ifdef yyget_extra
#define hspice_get_extra_ALREADY_DEFINED
#else
#define yyget_extra hspice_get_extra
#endif

#ifdef yyset_extra
#define hspice_set_extra_ALREADY_DEFINED
#else
#define yyset_extra hspice_set_extra
#endif

#ifdef yyget_in
#define hspice_get_in_ALREADY_DEFINED
#else
#define yyget_in hspice_get_in
#endif

#ifdef yyset_in
#define hspice_set_in_ALREADY_DEFINED
#else
#define yyset_in hspice_set_in
#endif

#ifdef yyget_out
#define hspice_get_out_ALREADY_DEFINED
#else
#define yyget_out hspice_get_out
#endif

#ifdef yyset_out
#define hspice_set_out_ALREADY_DEFINED
#else
#define yyset_out hspice_set_out
#endif

#ifdef yyget_leng
#define hspice_get_leng_ALREADY_DEFINED
#else
#define yyget_leng hspice_get_leng
#endif

#ifdef yyget_text
#define hspice_get_text_ALREADY_DEFINED
#else
#define yyget_text hspice_get_text
#endif

#ifdef yyget_lineno
#define hspice_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno hspice_get_lineno
#endif

#ifdef yyset_lineno
#define hspice_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno hspice_set_lineno
#endif

#ifdef yywrap
#define hspice_wrap_ALREADY_DEFINED
#else
#define yywrap hspice_wrap
#endif

#ifdef yyalloc
#define hspice_alloc_ALREADY_DEFINED
#else
#define yyalloc hspice_alloc
#endif

#ifdef yyrealloc
#define hspice_realloc_ALREADY_DEFINED
#else
#define yyrealloc hspice_realloc
#endif

#ifdef yyfree
#define hspice_free_ALREADY_DEFINED
#else
#define yyfree hspice_free
#endif

#ifdef yytext
#define hspice_text_ALREADY_DEFINED
#else
#define yytext hspice_text
#endif

#ifdef yyleng
#define hspice_leng_ALREADY_DEFINED
#else
#define yyleng hspice_leng
#endif

#ifdef yyin
#define hspice_in_ALREADY_DEFINED
#else
#define yyin hspice_in
#endif

#ifdef yyout
#define hspice_out_ALREADY_DEFINED
#else
#define yyout hspice_out
#endif

#ifdef yy_flex_debug
#define hspice__flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug hspice__flex_debug
#endif

#ifdef yylineno
#define hspice_lineno_ALREADY_DEFINED
#else
#define yylineno hspice_lineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 25
#define YY_END_OF_BUFFER 26
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[193] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   26,   24,   22,   24,   24,   24,
       23,    1,   24,   19,   24,   22,   24,   14,   16,   14,
       12,   10,   15,   12,   23,   19,   21,   20,   21,   25,
        4,    5,    7,   18,   17,   22,    0,    0,    0,    0,
        0,    0,    1,    0,   23,    1,    0,    0,    0,    0,
        0,    0,   13,   22,    0,   14,    0,   11,   12,   11,
       12,   12,   12,   12,   12,   11,   10,   11,   12,   11,
       11,   12,   23,    0,   20,   20,    0,    4,    5,    7,
        0,    0,    0,    0,    0,    0,    0,    0,   11,   11,

       11,   14,   11,   11,   14,   11,   12,   11,   11,   12,
       12,   12,   12,   12,   14,   12,   11,   12,   12,   11,
       12,   12,    2,    0,    0,    0,    2,    0,    0,    0,
       11,    0,   11,   11,    0,   11,   14,   14,   11,   14,
       14,    0,   12,   11,   12,   12,   11,   12,   12,    2,
       12,   12,   12,   12,    2,    2,    0,    0,    0,    0,
        2,    1,    0,    0,    0,    0,   11,    0,    0,   11,
        0,    0,   14,   12,    8,   12,   12,   12,    3,    9,
        0,    3,    9,    0,    0,    3,    9,   12,    6,    6,
        6,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    5,    1,    1,    1,    6,    1,
        1,    7,    8,    1,    9,   10,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,    1,    1,
       13,    1,    1,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       23,   30,   31,   32,   33,   34,   23,   23,   23,   23,
        1,    1,    1,    1,   23,    1,   14,   15,   16,   17,

       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   23,   30,   31,   32,   33,   34,   23,   23,
       23,   23,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[35] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    2,    3,    4,
        4,    3,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3
    } ;

static const flex_int16_t yy_base[208] =
    {   0,
        0,    4,   14,   27,    9,   38,   42,   55,   68,   81,
       94,  107,  116,  118,  508,  567,  567,  122,  105,  124,
      135,  567,  126,  129,  137,  140,  140,    0,  567,   42,
      133,  164,  567,  142,  505,  567,  567,  152,  153,  567,
        0,    0,    0,  567,  567,  567,  167,  479,  477,  490,
      468,  196,  567,  198,  201,  567,  203,  205,  207,  209,
      211,  159,  567,  214,  214,    0,  488,  240,    0,  266,
      471,  469,  482,  462,  216,  476,    0,  220,  296,  301,
      215,  230,  491,  232,  567,  239,  216,    0,    0,    0,
      475,  464,  427,  439,  299,  308,  314,  327,  333,  434,

        0,  325,  354,  318,  422,    0,  362,  375,  328,  418,
      412,  398,  380,  392,  390,  315,  366,  378,  396,  383,
      405,  410,  421,  382,  379,  365,  424,  394,  417,  429,
      567,  426,  432,  419,  358,  432,  351,  338,  320,  318,
      315,  326,  316,  351,  305,  301,  291,  289,  253,  445,
      235,  232,  227,  447,  465,  352,  458,  204,  151,  141,
      468,  461,  470,  474,  476,  479,  365,  137,  129,  118,
      110,   91,   78,   76,    0,   68,   65,   56,  567,  567,
       46,  481,  483,  485,   39,    0,    0,   33,  567,  487,
        0,  567,  517,  521,  525,  529,  533,  537,  541,  545,

      549,  552,  553,  556,  558,  560,  562
    } ;

static const flex_int16_t yy_def[208] =
    {   0,
      193,  194,  195,  195,  196,  196,  197,  197,  198,  198,
      199,  199,  200,  200,  192,  192,  192,  192,  192,  201,
      201,  192,  192,  201,  201,  192,  192,  202,  192,  202,
      203,  192,  192,  204,  192,  192,  192,  192,  192,  192,
      205,  206,  207,  192,  192,  192,  192,  192,  192,  192,
      192,  201,  192,  192,  201,  192,  192,  201,  201,  201,
      201,  192,  192,  192,  192,  202,  192,  192,  203,  192,
      203,  203,  203,  203,  204,   70,   32,  204,  204,   79,
       80,   79,  192,  192,  192,  192,  192,  205,  206,  207,
      192,  192,  192,  192,  201,  201,  201,  201,  192,   99,

      202,  202,  202,  103,  202,  203,  203,  203,  108,  203,
      203,  203,  203,  203,  202,   79,   32,   79,   79,   79,
       79,   79,  192,  192,  192,  192,  201,  201,  201,  201,
      192,  192,  192,  133,  192,   68,  202,  202,  202,  202,
      202,  192,  203,   70,  203,  203,  203,  203,  203,  203,
      203,  203,  203,   79,  192,  192,  192,  192,  192,  192,
      201,  192,  192,  201,  201,  201,   99,  192,  192,  192,
      192,  192,  202,  203,  203,  203,  203,  203,  192,  192,
      192,  201,  201,  201,  192,  203,  203,  203,  192,  201,
      203,    0,  192,  192,  192,  192,  192,  192,  192,  192,

      192,  192,  192,  192,  192,  192,  192
    } ;

static const flex_int16_t yy_nxt[602] =
    {   0,
      192,  192,   17,   18,  192,   21,   22,   23,  192,   19,
       24,   38,   39,   25,   16,   16,   26,   27,   28,   29,
       16,   30,   30,   31,   16,   32,   33,   16,   35,   26,
       27,   28,   29,   36,   30,   30,   31,   16,   32,   33,
       38,   39,   16,   16,   40,   16,   16,   16,   16,   16,
       16,   67,   16,   68,   16,   16,   16,   40,   16,   16,
       16,   16,   16,   16,  191,   16,  131,   16,   16,   16,
       40,   16,   16,   16,   16,   16,   16,  189,   16,  188,
       16,   16,   16,   40,   16,   16,   16,   16,   16,   16,
      187,   16,  186,   16,   16,   16,   40,   16,   16,   16,

       16,   16,   16,  106,   16,  101,   16,   16,   16,   40,
       16,   16,   16,   16,   16,   16,  131,   16,   40,   16,
       40,   45,   48,   45,   46,   47,   53,   54,   56,   57,
       49,   53,   54,   50,  133,   51,   55,   53,   54,   53,
       54,   62,   64,   65,   70,  131,   66,   63,  133,   66,
       71,   69,   69,   84,   58,   86,   87,  185,   72,   85,
       62,   73,   59,   74,  181,   60,   63,   61,   66,   46,
       47,   66,   75,   76,   69,   77,  180,   78,   75,   75,
       75,   79,   80,   80,   78,   75,   75,   80,   75,   81,
       80,   82,   80,   75,   78,   80,   80,   78,   53,   54,

       53,   54,   55,   53,   54,   56,   57,   53,   54,   53,
       54,   53,   54,   53,   54,   62,   64,   65,   86,   87,
       66,   63,   97,   66,   66,   69,   69,   66,  179,   69,
       69,   95,  119,   84,   96,  120,  121,   66,   75,   85,
       84,   75,  178,   98,   66,  177,   85,   66,   66,  100,
      122,   68,  176,  101,   66,   66,   66,  102,  103,  103,
      101,   66,   66,  103,   66,  104,  103,  105,  103,   66,
      101,  103,  103,  101,   69,   69,   69,   70,  106,  106,
       69,   69,   69,  107,  108,  108,  106,   69,   69,  108,
       69,  109,  108,  110,  108,   69,  106,  108,  108,  106,

       66,   53,   54,  115,  116,   69,   69,  117,   66,   75,
       53,   54,   75,  108,   78,  127,   53,   54,  106,   78,
      108,   78,   66,   75,  128,  174,  118,  144,   82,   53,
       54,   78,  115,  115,   78,  138,  136,  167,  139,  140,
      101,  130,  103,  129,   99,  146,  131,  101,  147,  148,
      132,  133,  133,  131,  156,  157,  133,  103,  134,  133,
      135,  133,  144,  131,  133,  133,  131,  101,   69,  142,
      143,  173,  101,  144,  101,   69,  167,  117,  172,  137,
      160,  105,  192,   75,  101,   66,   75,  101,  106,   75,
       66,   75,  159,  106,   75,  106,   53,   54,  154,  158,

      145,  136,  110,   66,   75,  106,  153,   75,  106,  152,
       78,  164,   66,   75,  151,   80,   75,   66,   75,   53,
       54,   75,  155,  156,  157,  161,  162,  163,  150,   80,
      165,   53,   54,  142,  142,   78,  169,  167,  149,  170,
      171,  192,  141,  136,  166,  131,  155,  156,  157,   66,
      131,  192,  131,  126,   66,   75,  125,  168,   75,  135,
      156,  157,  131,  156,  157,  131,  155,  156,  157,  161,
      162,  163,  162,  163,   78,  175,   53,   54,   53,   54,
      124,   53,   54,   53,   54,   53,   54,   53,   54,   53,
       54,  123,   83,   69,  114,  113,  112,  111,  182,   99,

       94,  183,  184,   93,   92,   91,   83,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  190,   16,   16,   16,
       16,   20,   20,   20,   20,   34,   34,   34,   34,   37,
       37,   37,   37,   41,   41,   41,   41,   42,   42,   42,
       42,   43,   43,   43,   43,   44,   44,   44,   44,   52,
       52,   52,   52,   66,   66,   69,   69,   75,   75,   75,
       88,   88,   89,   89,   90,   90,   15,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,

      192
    } ;

static const flex_int16_t yy_chk[602] =
    {   0,
        0,    0,    1,    1,    0,    2,    2,    2,    0,    1,
        2,    5,    5,    2,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        6,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        7,   30,    7,   30,    7,    8,    8,    8,    8,    8,
        8,    8,    8,    8,  188,    8,  185,    8,    9,    9,
        9,    9,    9,    9,    9,    9,    9,  181,    9,  178,
        9,   10,   10,   10,   10,   10,   10,   10,   10,   10,
      177,   10,  176,   10,   11,   11,   11,   11,   11,   11,

       11,   11,   11,  174,   11,  173,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,  172,   12,   13,   12,
       14,   13,   19,   14,   18,   18,   20,   20,   23,   23,
       19,   24,   24,   19,  171,   19,   21,   21,   21,   25,
       25,   26,   27,   27,   31,  170,   34,   26,  169,   34,
       31,   34,   34,   38,   25,   39,   39,  168,   31,   38,
       62,   31,   25,   31,  160,   25,   62,   25,   32,   47,
       47,   32,   32,   32,   32,   32,  159,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   52,   52,

       54,   54,   55,   55,   55,   57,   57,   58,   58,   59,
       59,   60,   60,   61,   61,   64,   65,   65,   87,   87,
       75,   64,   60,   75,   78,   75,   75,   78,  158,   78,
       78,   58,   81,   84,   59,   81,   81,   82,   82,   84,
       86,   82,  153,   61,   68,  152,   86,   68,   68,   68,
       82,   68,  151,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   70,   70,   70,   70,  149,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,

       79,   95,   95,   79,   79,   79,   79,   79,   80,   80,
       96,   96,   80,  148,   80,   95,   97,   97,  147,   80,
      146,   80,  116,  116,   96,  145,   80,  143,   80,   98,
       98,   80,  102,  102,   80,  104,  102,  142,  104,  104,
      141,   98,  140,   97,   99,  109,   99,  139,  109,  109,
       99,   99,   99,   99,  156,  156,   99,  138,   99,   99,
       99,   99,  144,   99,   99,   99,   99,  103,  144,  107,
      107,  137,  103,  107,  103,  117,  167,  117,  135,  103,
      126,  103,  167,  117,  103,  118,  118,  103,  108,  118,
      120,  120,  125,  108,  120,  108,  128,  128,  118,  124,

      108,  115,  108,  119,  119,  108,  114,  119,  108,  113,
      120,  128,  121,  121,  112,  119,  121,  122,  122,  129,
      129,  122,  123,  123,  123,  127,  127,  127,  111,  121,
      129,  130,  130,  132,  132,  122,  134,  132,  110,  134,
      134,  136,  105,  136,  130,  133,  150,  150,  150,  136,
      133,  100,  133,   94,  154,  154,   93,  133,  154,  133,
      157,  157,  133,  162,  162,  133,  155,  155,  155,  161,
      161,  161,  163,  163,  154,  150,  164,  164,  165,  165,
       92,  166,  166,  182,  182,  183,  183,  184,  184,  190,
      190,   91,   83,   76,   74,   73,   72,   71,  164,   67,

       51,  165,  166,   50,   49,   48,   35,   15,    0,    0,
        0,    0,    0,    0,    0,    0,  184,  193,  193,  193,
      193,  194,  194,  194,  194,  195,  195,  195,  195,  196,
      196,  196,  196,  197,  197,  197,  197,  198,  198,  198,
      198,  199,  199,  199,  199,  200,  200,  200,  200,  201,
      201,  201,  201,  202,  202,  203,  203,  204,  204,  204,
      205,  205,  206,  206,  207,  207,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  192,  192,  192,  192,  192,  192,

      192
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[26] =
    {   0,
1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 
    1, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
#line 3 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
/**
 * @file Lexer of HSPICE-compatible circuit description
 */

/*
 *  FastCSIM Copyright (C) 2021 cassuto                                    
 *  This project is free edition{} you can redistribute it and/or          
 *  modify it under the terms of the GNU Lesser General Public             
 *  License(LGPL) as published by the Free Software Foundation{} either     
 *  version 2.1 of the License, or (at your option) any later version.     
 *                                                                         
 *  This project is distributed in the hope that it will be useful,        
 *  but WITHOUT ANY WARRANTY{} without even the implied warranty of        
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU      
 *  Lesser General Public License for more details.                        
 */
#include <iostream>
#include "csim/internal/parser/algebraic-defs.h"
#include "csim/internal/parser/hspice-defs.h"
#include "parse-hspice.h"
#line 949 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.cc"
/* Symbol of nodes */
/* For algebraic expression */
/* Actions */

#line 954 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.cc"

#define INITIAL 0
#define STARTUP 1
#define COMMENT 2
#define MODEL_NAME 3
#define MODEL_TYPE 4
#define SUBCKT 5
#define ALGEBRAIC_EXP 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 55 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"


#line 58 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
 /* title line */
#line 1185 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 193 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 567 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = (yy_more_len); yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 59 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    hspice_lval.text = strdup (hspice_text);
    BEGIN(STARTUP);
    return K_Title;
}
	YY_BREAK
/* .end */
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 67 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    return K_End;
}
	YY_BREAK
/* .model */
case 3:
YY_RULE_SETUP
#line 73 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    BEGIN(MODEL_NAME);
    return K_Model;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 77 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    hspice_lval.text = strdup (hspice_text);
    BEGIN(MODEL_TYPE);
    return K_Text;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 82 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    hspice_lval.text = strdup (hspice_text);
    BEGIN(STARTUP);
    return K_ModelType;
}
	YY_BREAK
/* .subckt */
case 6:
YY_RULE_SETUP
#line 90 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    BEGIN(SUBCKT);
    return K_Subckt;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 94 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    hspice_lval.text = strdup (hspice_text);
    BEGIN(STARTUP);
    return K_Text;
}
	YY_BREAK
/* .ends */
case 8:
YY_RULE_SETUP
#line 100 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    return K_Ends;
}
	YY_BREAK
/* .param */
case 9:
YY_RULE_SETUP
#line 106 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    BEGIN(STARTUP);
    return K_Param;
}
	YY_BREAK
/* Text of unsigned digits  */
case 10:
YY_RULE_SETUP
#line 112 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    hspice_lval.text = strdup (hspice_text);
    return K_Unsigned;
}
	YY_BREAK
/* Signed integers or floats */
case 11:
YY_RULE_SETUP
#line 118 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    hspice_lval.text = strdup (hspice_text);
    return K_Number;
}
	YY_BREAK
/* Text */
case 12:
YY_RULE_SETUP
#line 124 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    hspice_lval.text = strdup (hspice_text);
    return K_Text;
}
	YY_BREAK
/* Line continuation */
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 130 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{ }
	YY_BREAK
/* Nodes (After TEXT mismatched) */
case 14:
YY_RULE_SETUP
#line 133 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    hspice_lval.text = strdup (hspice_text);
    return K_Nodes;
}
	YY_BREAK
/* Equ */
case 15:
YY_RULE_SETUP
#line 139 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    return K_Equ;
}
	YY_BREAK
/* Algebraic expression */
case 16:
YY_RULE_SETUP
#line 144 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    BEGIN(ALGEBRAIC_EXP);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 147 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    BEGIN(STARTUP);
    hspice_lval.text = strdup(hspice_text);
    hspice_lval.text[strlen(hspice_lval.text)-1] = '\0';
    return K_Algebraic;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 153 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{ yymore(); }
	YY_BREAK
/* Begin of a comment line */
case 19:
YY_RULE_SETUP
#line 157 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    BEGIN(COMMENT);
}
	YY_BREAK
/* End of a comment (May be accompanied with line continuation) */
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 161 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{
    BEGIN(STARTUP);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 164 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{ }
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 166 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{ /* skip EOLs */ }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 168 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{ /* skip leading spaces */ }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 170 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
{ /* skip any other chars */ }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 173 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"
ECHO;
	YY_BREAK
#line 1457 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STARTUP):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(MODEL_NAME):
case YY_STATE_EOF(MODEL_TYPE):
case YY_STATE_EOF(SUBCKT):
case YY_STATE_EOF(ALGEBRAIC_EXP):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 193 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 193 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 192);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 173 "/cygdrive/e/FastCSIM/core/parser/lex-hspice.lpp"


int yywrap() {
    {BEGIN INITIAL;}
    return 1;
}

